name: Evaluate LLM Output

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest  # Use the latest Ubuntu operating system

    env:
      OPENAI_API_KEY: sk-proj-KPBo2qv14PNo64Vo31XBT3BlbkFJNPUOW9djeUNxsBjoH8z4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Golden Standard
        run: |
          python -W ignore generate_golden_standard.py

      - name: Generate and Evaluate LLM Output
        run: |
          python -W ignore evaluate_llm_output.py

      - name: Save evaluation results
        run: |
          cat evaluation_results.json
        if: always()  # Ensures this step runs even if previous steps fail

      - name: Upload evaluation results
        uses: actions/upload-artifact@v2
        with:
          name: evaluation-results
          path: evaluation_results.json
